### ISSUE TITLE
OpenStudio for Jupyter Notebooks

### ISSUE THREAD

**Issue by ted-strauss-K1** [moodleou/moodle-mod_openstudio#3]
Hello,
This discussion thread https://moodle.org/mod/forum/discuss.php?d=362641  suggests that this plugin could be used to integrate Jupyter notebooks into moodle. 

Does anyone know if there's a way to do that?

Thank you

**Comment by jason-platts** [comment]
We either display the html from the nbk in an iframe or directly inject the content into the page (ipynb).

See https://github.com/moodleou/moodle-mod_openstudio/blob/master/classes/local/renderer_utils.php

`
$fs = get_file_storage();
                if ($contentfiles = $fs->get_area_files($context->id, 'mod_openstudio', 'notebook', $contentdata->fileid)) {
                    if ($contentarea == 'contentversion') {
                        $contentarea = 'notebookversion';
                    } else {
                        $contentarea = 'notebook';
                    }
                    $contenttypeiframe = true;
                    $ipynbfilecontent = '';
                    foreach ($contentfiles as $contentfile) {
                        $filename = $contentfile->get_filename();
                        if ($contentfile->get_mimetype() == 'application/x-ipynb+json') {
                            $ipynbfilecontent = $contentfile->get_content();
                        }
                        if ($filename != '.') {
                            $extension = pathinfo($filename, PATHINFO_EXTENSION);
                            $contentfileurls[$extension] = self::make_plugin_file($context->id, $contentarea,
                                    $contentdata->id, $filename, $folderid);
                        }
                    }
                    $contentiframesrc = isset($contentfileurls['html']) ? $contentfileurls['html'] : '';
                    // When we only upload ipynb file.
                    if (empty($contentfileurls['html']) && !empty($contentfileurls['ipynb']) && !empty($ipynbfilecontent)) {
                        $contentiframesrc = '';
                        $previewcontent = $ipynbfilecontent;
                    }
                    $contentfileurl = $contentfileurls['ipynb'] . '?forcedownload=true';
                    break; // Only if this is a notebook.
                }
`
